// Code generated by ogen, DO NOT EDIT.

package petstore

// setDefaults set default value of fields.
func (s *Order) setDefaults() {
	{
		val := int32(1)
		s.Quantity.SetTo(val)
	}
	{
		val := bool(false)
		s.Complete.SetTo(val)
	}
}
