// Code generated by ogen, DO NOT EDIT.
package petstore

type DeleteOrderRes interface {
	deleteOrderRes()
}

type DeleteUserRes interface {
	deleteUserRes()
}

type FindPetsByStatusRes interface {
	findPetsByStatusRes()
}

type FindPetsByTagsRes interface {
	findPetsByTagsRes()
}

type GetOrderByIdRes interface {
	getOrderByIdRes()
}

type GetPetByIdRes interface {
	getPetByIdRes()
}

type GetUserByNameRes interface {
	getUserByNameRes()
}

type LoginUserRes interface {
	loginUserRes()
}

type UpdatePetRes interface {
	updatePetRes()
}

type UpdateUserRes interface {
	updateUserRes()
}
